/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated by Next.js, but we include it
// in this scaffolding so TypeScript can work immediately.

